load("train_data.RData")
load("train_index.RData")
load("test_data.RData")
load("test_index.RData")
ls() #returns a list of all the objects you just loaded (and anything else in your environment)
write.csv(train_data,  file="train_data.csv")
write.csv(train_index, file="train_index.csv")
write.csv(test_data, file="test_data.csv")
write.csv(test_index, file="test_index.csv")
